global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'booking_service'
    static_configs:
      - targets: ['booking-service:3002']

  - job_name: 'event_service'
    static_configs:
      - targets: ['event-service:3003']

  - job_name: 'payment_service'
    static_configs:
      - targets: ['payment-service:3004']

  - job_name: 'notification_service'
    static_configs:
      - targets: ['notification-service:3005']
